### ISSUE TITLE
Rückmeldungen von Matthias Stürmer

### ISSUE THREAD

**Issue by rastrau** [ebp-group/embag-check#3]
![image](https://github.com/ebp-group/embag-check/assets/4510815/7ecf7c4b-c5dc-43eb-ab87-ba053fc142d4)

Vgl. https://www.linkedin.com/feed/update/urn:li:activity:7213406721589866497?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7213406721589866497%2C7214166360002568192%29

- [x] Typo (doppeltes "wird")
- [x]  Punkt zu Werkverträgen
- [x] Detaillierungsgrad Beschreibung OSS-Lizenzen
- [x] Wording bezüglich OSS-Lizenzen ("contagious" für "viral")

**Comment by metaodi** [comment]
Gemäss [Copyleft - Wikipedia](https://de.wikipedia.org/wiki/Copyleft) ist der Begriff "viral" oder "contagious" negativ konotiert: «Microsoft hat in seiner eigennützigen Anti-Linux-Strategie das kritische Schlagwort viral für das Copyleft eingeführt, um das Bild eines Schädlings zu zeichnen, der alle Erweiterungen befalle und die Möglichkeit einer Entlohnung durch Lizenzgebühren bösartig abtöte, wodurch letztlich das geistige Eigentum von Firmen bedroht werde»

**Comment by metaodi** [comment]
Wording ist angepasst bezüglich Copyleft: "diese verlangen, dass alle Änderungen der Software frei verfügbar bleiben"

**Comment by metaodi** [comment]
Zusätzlich habe ich noch Links zu https://choosealicense.com/ hinzugefügt um etwas mehr Infos zu den Lizenzen zu erhalten.
